"""The LLM driving guide, embedded so it travels with the package.

`websurf skill` prints it with paths resolved for THIS install;
`websurf skill --install` writes it where Claude Code discovers skills
(~/.claude/skills/websurf/SKILL.md). Single source of truth: the installed
copy is generated — never hand-edit it, edit TEMPLATE here and re-install.

Sentinels (plain .replace — the text itself contains shell `$VARS` and
brace-y flag syntax, so str.format/Template would misfire):
  __PY__    the interpreter running this package
  __PKG__   the package directory
  __ROOT__  the package's parent (repo root; README lives here)
  __CACHE__ the default store — the per-user cache DB
"""
import sys
from pathlib import Path

PKG = Path(__file__).resolve().parent

TEMPLATE = """\
---
name: websurf
description: Browse websites and extract structured data from them. Use for navigational asks — "what's on this site", "list everything this section links to", "read across these pages" — and for dataset asks — "pull the same fields from these pages", "build a dataset from this site". Deterministic outlines, exhaustive link listings, JS handling, enforced politeness, JSONL extraction.
---

<!-- Generated by `websurf skill --install`. Do NOT hand-edit: the canonical
     text lives in websurf/skill.py; regenerate after upgrading the tool. -->

# websurf — browse and extract, deterministically

Tool package: `__PKG__`
Full docs: `__ROOT__/README.md`. All state (page cache, runs, records, cached
extractors) lives in ONE SQLite file per `--db` path.

```sh
WEBSURF="__PY__ __PKG__/__main__.py"
```

## Two modes — pick one first

**BROWSING** (surveying, enumerating, reading — no dataset artifact): drive
`probe` / `expand` / `text` directly, results go into the conversation, and
the default store is correct — it's a self-cleaning cache, nothing durable
accumulates. Zero LLM tokens beyond what you read. Prefer this over one-off
page fetches for anything spanning more than a page or two: outlines and link
listings are exhaustive and checkable where a summary is lossy, revisits are
cache hits, and politeness is enforced even when you loop.

**DATASET** (the user keeps an artifact): same primitives plus
`synthesize` / `extract` (or autonomous `run`), and pass
`--db <path-in-their-project>`. Browsing escalates to dataset work in place —
same cache, nothing re-fetched — but move to a project `--db` at the point
the user says "keep/export this".

## Storage

The default store (`__CACHE__`) is a per-user CACHE — pages older than
`--max-age` (7d) are pruned automatically on open, and deleting the file is
always safe. Explicit `--db` stores are the user's: durable, never
auto-pruned, self-contained (cache + extractors + records travel with the
project — easy to hand off, re-run, or delete).

`--db` is a GLOBAL flag — it goes BEFORE the subcommand
(`$WEBSURF --db ./project.db run ...`), not after (a subcommand won't accept
it). Use the SAME `--db` for every step of one job so they share the cache (a
`probe` under one DB won't be seen by an `extract` under another).
Read-only commands (`status`, `runs`, `report`, `export`) never create a
store; `prune [--all]` reclaims space in any store.

## Extract cheaply — decide BEFORE you crawl

Cost is almost entirely LLM calls. The game: do the cheapest thing that gets
the data, and **always `probe` first**. Cost ladder, cheapest first — take the
highest rung that works:

1. **Structured data — free.** If `probe` shows `structured_data` (JSON-LD/OG),
   the fields extract with zero LLM tokens. Common on product, article, event,
   and listing pages.
2. **Data islands — free-to-one-call.** JS-built sites (Next.js/Nuxt/SPAs)
   usually ship their FULL data as JSON inside the page. `probe` surfaces it as
   `data_islands` (selector + array paths + item keys + a sample item) — often
   enough to hand-write an island spec yourself for ZERO tokens:
   `{"kind":"island","island_selector":"script#__NEXT_DATA__",
     "path":"props.pageProps.items","fields":{"name":"title"}}`
   Otherwise one `synthesize` writes it. Never render a page whose data is
   already in an island (health `data_shell` = exactly this).
3. **Synthesize once, apply to siblings — one LLM call per page-template.**
   When many pages share a template (a paginated list, or N detail pages with
   the same layout), `synthesize` writes one extractor from 1–2 samples and
   `extract` applies it deterministically to all of them. Cost is O(templates),
   not O(pages); specs are cached so re-runs are free. **This is the default
   path for any real dataset.**
4. **Per-page LLM read — last resort.** Only for hostile/one-off pages where no
   spec holds. You pay per page.

`run` (autonomous) sits *on top* of these and **adds** planning-LLM calls.
It is the fallback for when you can't see the structure yourself — **not** the
default. You are usually the cheapest planner.

### The decision, concretely

1. `probe` the start URL; read the outline.
2. `structured_data_types` non-empty? → `fetch` + `extract` (structured-data
   path, ~zero tokens). `microdata` non-empty? → its `props` are your selector
   hooks: `synthesize` will use `[itemprop=...]`.
3. **Is all the wanted data already on the listing/start page(s)?** Read the
   outline's `repeats`: blocks with high `avg_text_chars` whose `sample_text`
   shows your fields mean the items are ON this page — extract from THOSE
   pages; do not fan out. `contains_group` naming a link group means those
   detail links are the very items you're looking at. (A listing that already
   shows every wanted field needs the ~N list pages, not the 1,000 detail
   pages — fanning out is ~20× the fetches for the same data.)
4. **Many pages, one template** (pagination, or uniform detail pages)? →
   enumerate the pages (see pagination gotcha), `synthesize` from 2 samples,
   `extract` across all. One LLM call.
5. **Structure unclear / multi-template / needs navigation you can't
   predetermine?** → `run` (it plans for you; a few k planning tokens).

## Commands

Primitives — you plan; no LLM except `synthesize`:

```sh
$WEBSURF probe URL                  # outline: title/headings/JSON-LD/microdata/data_islands/link groups WITH COUNTS + repeats + next_page
$WEBSURF expand URL "host/dir/*"    # list every link in a group of a fetched page ('*' = all links)
$WEBSURF sitemap SITE [--filter S]  # URL patterns from the site's sitemap(s) — the link source when a JS listing has none
$WEBSURF fetch URL...               # into cache; prints health (ok/data_shell/js_shell/blocked/denied/...)
                                     #   >80 URLs on one domain? add --cap-per-domain N FIRST
$WEBSURF text URL                   # readability main-text of a cached page
$WEBSURF synthesize U1 U2 --fields a,b,c   # !! THE LLM CALL !! one extractor spec from samples (sees data_islands too)
$WEBSURF extract URL... --spec spec.json   # deterministic apply -> JSONL records (CSS or island specs); NEVER renders
$WEBSURF status / runs / report --run N / prune [--all]
```

Autonomous — adds planning-LLM calls; the fallback, not the default:

```sh
$WEBSURF run "objective" URL... --fields name,description,url   # multiple URLs merge into ONE dataset
$WEBSURF export --run N --out file.jsonl
```

`run` flags: `--cap-per-group N` (fan-out width, default 30), `--cap-pages N`
(pages/run, default 300), `--cap-per-domain N` (new fetches per domain, default
80 — raise for any single-site job > 80 pages), `--allow-external` (cross-domain
enrichment, OFF by default), `--budget-tokens N` (hard stop, default 400k),
`--budget-renders N` (browser renders, default 400 — a circuit breaker, not a
working limit; rendering is on-demand for shells), `--no-render-breaker`
(keep auto-rendering a domain whose renders keep classifying soft_404 —
see "Sample before you sweep"), `--mode manual` (pause at
fan-outs), `--max-age DAYS` (cache freshness, default 7), `--min-delay SECONDS`
(per-domain pacing, default 2 — see "Pacing"), `--backend {auto,api,cli}`.

The LLM backend auto-selects: `ANTHROPIC_API_KEY` + the `anthropic` package if
present, else the `claude` CLI on the machine's session auth.

## Gotchas that cost money or silently lose data

- **`synthesize` IS an LLM call** — the only primitive that spends tokens
  (probe/expand/fetch/text/extract are all free). Synthesize ONCE per template
  from 2 samples; never per page.
- **Caps clamp loudly → but the data is still incomplete.** Defaults:
  `cap-per-group=30`, `cap-pages=300`, `cap-per-domain=80`. Hitting one means a
  partial dataset. `fetch` prints a `!! CAPPED` summary and `report --run N`
  lists every clamp — raise the *specific* cap deliberately, don't just re-run.
  **Count the URLs before a big single-domain batch**: 100+ detail pages on one
  site needs `fetch --cap-per-domain <count>` up front — `fetch` pre-flight
  warns on stderr when the URLs you passed already exceed the cap (capped URLs return
  health `domain_capped`; the ceiling counts new fetches this invocation —
  cache hits are free, so re-running with the flag fetches only the missing
  ones). (The outline's `singles_omitted` is NOT a cap: it's a display limit
  only — extraction reads full HTML; `expand URL '*'` lists every link.)
- **JS-heavy sites: render is the LAST resort, not the first move.** The ladder
  when `probe`/`fetch` says shell: (1) health `data_shell` → the data is in an
  embedded JSON island; extract it, done, zero renders. (2) `js_shell` with no
  links to expand → `sitemap SITE` usually lists every entity URL, and detail
  pages are often server-rendered (og:title/og:description extract via
  `{"sel": "meta[property=og:title]", "attr": "content"}`) even when listings
  aren't. (3) Only then render (`--playwright`, or the automatic fallback).
  Renders are budgeted (default 400, a circuit breaker): a shell left
  un-rendered by the budget is kept but COUNTED — `!! CAPPED` summary says so,
  and the cached shell is retried automatically on the next invocation with
  budget. A silent shell-as-data is a bug, not a behavior.
  **Sample before you sweep**: before rendering more than ~20 shell siblings
  (e.g. every sitemap `/portfolio/*` URL), render 3–5 first and check (a) the
  health mix — SPAs serve HTTP 200 + a not-found shell for deleted entities,
  visible as `soft_404` only AFTER the render — and (b) whether the plain
  HTML already yields the fields (live detail pages often do, via og/meta or
  server-rendered text), making the sweep unnecessary. The tool backstops
  runaway sweeps: once >=70% of >=10 rendered pages on a domain classify
  soft_404, the render breaker stops auto-rendering that domain, notes the
  trip on stderr, and lists the skipped shells in the `!! CAPPED` summary
  (`--no-render-breaker` overrides; explicit `--playwright` is never blocked).
  (4) **All three rungs empty → fail fast, don't improvise.** If the listing
  is `js_shell` with no `data_islands`, a probed DETAIL page is the same
  shell (no islands, no `og`, no `structured_data_types`), and `sitemap`
  yields no entity URLs, the data only exists behind rendering or
  interaction. That is a finding, not a failure: report it and stop, or opt
  in deliberately (`fetch --playwright URL...` with a render budget you
  chose). Never hand-roll a scraper around the tool to route past this.
- **`extract` never renders.** It applies the spec to cached or plainly-fetched
  HTML — island and meta specs *want* the un-rendered shell, so `js_shell`
  health during extract is normal, not an error. If a spec targets DOM that
  only exists after JS runs, `fetch --playwright URL...` first; extract then
  reads the rendered pages from cache. Per-page progress streams on stderr
  (`# [i/N] health records seconds url`) — a quiet extract IS a hang.
- **`groups: []` is normal, not a dead end.** Many sites list everything on one
  page (items as `singles`), or give each item a unique URL dir so no group
  forms (needs ≥4 links per dir). With nothing to `expand`, check `repeats`:
  the data is usually already on the page(s) — `fetch` + `synthesize`/`extract`,
  or let `run`'s fast path (≤8 start pages skips planning) handle it.
- **Pagination has no auto-follow in primitives.** `expand` only lists links on
  a page you already fetched. `probe` reports `next_page`; enumerate a chain by
  following it (probe page N → page N+1) or by obvious pattern
  (`…/page-1…page-50.html`). `run` follows pagination itself but only
  `cap_paginate=3` extra pages by default — raise `--cap-pages` for long catalogs.
- **Cache is reused within `--max-age` (7 days).** A re-`run` reuses cached
  pages (≈free); pass `--max-age 0` to force-refresh stale data.

## Pacing (the per-domain delay)

The tool waits `--min-delay` seconds between fetches to the *same* domain
(default 2.0). The effective wait is `max(min_delay, robots crawl-delay)` — a
site's own `crawl-delay` always wins if it's larger, and robots is honored
regardless. The delay only bites where one invocation fetches multiple pages on
one domain: `run` and `fetch URL...` (the single-page primitives never wait).

The knob is `--min-delay SECONDS`, on both `run` and `fetch`:

```sh
$WEBSURF run "..." URL --min-delay 5      # slower / gentler
$WEBSURF fetch URL... --min-delay 0.2     # faster
```

Higher = more seconds between fetches; lower = fewer. A single-domain crawl is
~`pages x min_delay` seconds of pacing (≈2 min for 50 pages at the default).
Cross-domain fetches don't wait on each other — the delay is per domain.

## Rules the tool enforces (don't fight them)

- Politeness: 2s/domain by default, robots honored. Tunable per run — see
  "Pacing (the per-domain delay)".
- ToS-hostile aggregators (LinkedIn, Crunchbase, PitchBook & co) are
  denylisted → health `denied`; the outline reports them under `links.denied`,
  never as fetchable groups.
- Fan-out capped by default; every clamp logged in `report`. Raising a cap is an
  explicit flag, never a code workaround.
- Hard budgets (metered, work stops when hit): 400k tokens, 400 fetches,
  400 renders.
- After code changes: `cd __ROOT__ && __PY__ -m websurf.selftest`
  (offline, zero tokens).

## Output

Records are domain-agnostic JSONL with provenance (`_source`, `_extractor`,
`_run`). For a specific downstream store: `export` JSONL first, then map
explicitly — the tool never writes another project's schema.
"""


def render():
    from websurf.config import default_db_path
    return (TEMPLATE
            .replace("__PY__", sys.executable)
            .replace("__PKG__", str(PKG))
            .replace("__ROOT__", str(PKG.parent))
            .replace("__CACHE__", default_db_path()))


def install(dest=None):
    """Write the rendered skill where Claude Code discovers it (or to dest)."""
    dest = Path(dest).expanduser() if dest else Path.home() / ".claude" / "skills" / "websurf"
    if dest.suffix != ".md":
        dest = dest / "SKILL.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(render())
    return dest
